name: Package Magisk Module

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Upload Artifact to CI
        uses: actions/upload-artifact@v6
        with:
          name: Featuresunlock_$(date +'%Y%m%d%H%M')
          path: |
            ./*
            !.git*
            !.github*
            !README.md
          retention-days: 90
