name: Package Magisk Module

on:
  push:
    branches: [ dev ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Upload Artifact to CI
        uses: actions/upload-artifact@v6
        with:
          name: module-package
          path: |
            customize.sh
            module.prop
            service.sh
            system.prop
            META-INF
            
